### ISSUE TITLE
GET /me is not working with the Basic authentication

### ISSUE THREAD

**Issue by estrada9166** [guestyorg/guesty-api#6]
The endpoint `/me` is returning `User not found` with the Basic authentication. How it should be requested to get the user info?

**Comment by aviadhahami** [comment]
We're using a variation of Basic called `Binasix` which is pretty much the same but you should transform the header to binary string and pad with six.
For example:
`Authorization: Basic myToken`  should be `Authorization: Binasix 60100010111011106`

Good luck! :love:

**Comment by estrada9166** [comment]
@aviadhahami not working for me, I'm encoding `key:secretKet` in base64 and then I transform the result to binary, padding 6 at the beginning and the end and then making the request with the header Authorization: Binasix 6010001011101110.............6
